services:
  backend:
    image: wifimemes/vegate-backend:latest
    command: http run
    networks:
      - vegate_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
      start_interval: 5s
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`vegate.jadore.dev`) && PathPrefix(`/api`)"
        - "traefik.http.routers.backend.service=vegate_stack_backend"
        - "traefik.http.routers.backend.entrypoints=web,websecure"
        - "traefik.http.services.vegate_stack_backend.loadbalancer.server.port=8000"
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 3s
        monitor: 1m

  deployment_monitor:
    image: wifimemes/vegate-backend:latest
    command: deployment monitor run
    networks:
      - vegate_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
      start_interval: 5s
    deploy:
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 3s
        monitor: 1m

  oms:
    image: wifimemes/vegate-backend:latest
    command: oms run --host 0.0.0.0 --port 8082
    networks:
      - vegate_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/v1/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
      start_interval: 5s
    deploy:
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 3s
        monitor: 1m

  ohlc_feed:
    image: wifimemes/vegate-backend:latest
    command: markets feed run --host 0.0.0.0 --port 8001
    networks:
      - vegate_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
      start_interval: 5s
    deploy:
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 3s
        monitor: 1m

  backtest_monitor:
    image: wifimemes/vegate-backend:latest
    command: backtest monitor run
    networks:
      - vegate_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
      start_interval: 5s
    deploy:
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 3s
        monitor: 1m

  outbox_poller:
    image: wifimemes/vegate-backend:latest
    command: outbox run
    networks:
      - vegate_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
      start_interval: 5s
    deploy:
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 3s
        monitor: 1m

  traefik:
    image: traefik:v3.6
    command:
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.swarm=true"
      - "--providers.swarm.network=vegate_network"
      - "--providers.docker=true"
      - "--providers.docker.network=vegate_network"
      - "--log.level=DEBUG"
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    networks:
      - vegate_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  postgres:
  redis:

networks:
  vegate_network:
    driver: overlay
    attachable: true
    external: true
