"""Created index in ticks idx_ticks_source_timestamp

Revision ID: 0019a7043609
Revises: f7b45f2ec509
Create Date: 2025-12-06 23:39:07.010827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0019a7043609'
down_revision: Union[str, Sequence[str], None] = 'f7b45f2ec509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticks', 'market_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('idx_ticks_source_timestamp', 'ticks', ['source', 'timestamp'], unique=False)
    op.drop_column('ticks', 'market_type_a')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticks', sa.Column('market_type_a', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('idx_ticks_source_timestamp', table_name='ticks')
    op.alter_column('ticks', 'market_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
