"""Added version_id to backtests

Revision ID: 080fd2bd66ce
Revises: e73d01721878
Create Date: 2026-05-27 16:18:08.049367

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "080fd2bd66ce"
down_revision: Union[str, Sequence[str], None] = "e73d01721878"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("backtests", sa.Column("version_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "backtests_strategy_version_id_fkey",
        "backtests",
        "strategy_versions",
        ["version_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.execute("""
    UPDATE backtests
    SET version_id = strategy.cur_version_id
    FROM strategy
    WHERE backtests.strategy_id = strategy.strategy_id
    """)
    op.alter_column("backtests", "version_id", nullable=False)

    op.drop_constraint(
        op.f("backtests_strategy_id_fkey"), "backtests", type_="foreignkey"
    )
    op.drop_column("backtests", "strategy_id")
    
    op.create_foreign_key(
        "strategy_cur_version_id_fkey",
        "strategy",
        "strategy_versions",
        ["cur_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("strategy_cur_version_id_fkey", "strategy", type_="foreignkey")

    op.add_column(
        "backtests",
        sa.Column("strategy_id", sa.UUID(), autoincrement=False, nullable=True),
    )

    op.execute("""
    UPDATE backtests
    SET strategy_id = strategy_versions.strategy_id
    FROM strategy_versions
    WHERE backtests.version_id = strategy_versions.id
    """)

    op.alter_column("backtests", "strategy_id", nullable=False)

    op.drop_constraint("backtests_strategy_version_id_fkey", "backtests", type_="foreignkey")

    op.create_foreign_key(
        op.f("backtests_strategy_id_fkey"),
        "backtests",
        "strategy",
        ["strategy_id"],
        ["strategy_id"],
        ondelete="CASCADE",
    )

    op.drop_column("backtests", "version_id")