"""Added version_id to strategy_deployments

Revision ID: 0cb2104874ae
Revises: 080fd2bd66ce
Create Date: 2026-05-27 17:51:50.530224

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0cb2104874ae"
down_revision: Union[str, Sequence[str], None] = "080fd2bd66ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "strategy_deployments", sa.Column("version_id", sa.UUID(), nullable=True)
    )
    op.execute(
    """
    UPDATE strategy_deployments sd
    SET version_id = (SELECT cur_version_id FROM strategy s WHERE s.strategy_id = sd.strategy_id);
    """)
    op.alter_column("strategy_deployments", "version_id", nullable=False)

    op.drop_constraint(
        op.f("strategy_deployments_strategy_id_fkey"),
        "strategy_deployments",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_strategy_versions_id",
        "strategy_deployments",
        "strategy_versions",
        ["version_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("strategy_deployments", "strategy_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Re-add strategy_id as nullable first so we can backfill it
    op.add_column(
        "strategy_deployments",
        sa.Column("strategy_id", sa.UUID(), nullable=True),
    )

    # Populate strategy_id from strategy_versions
    op.execute(
        """
        UPDATE strategy_deployments sd
        SET strategy_id = (
            SELECT sv.strategy_id
            FROM strategy_versions sv
            WHERE sv.id = sd.version_id
        );
        """
    )

    # Make strategy_id non-nullable again
    op.alter_column("strategy_deployments", "strategy_id", nullable=False)

    # Remove FK to strategy_versions
    op.drop_constraint(
        "fk_strategy_versions_id",
        "strategy_deployments",
        type_="foreignkey",
    )

    # Restore FK to strategy
    op.create_foreign_key(
        op.f("strategy_deployments_strategy_id_fkey"),
        "strategy_deployments",
        "strategy",
        ["strategy_id"],
        ["strategy_id"],
        ondelete="CASCADE",
    )

    # Drop version_id
    op.drop_column("strategy_deployments", "version_id")