"""Create ohlcs table, drop ohlc_levels table

Revision ID: 0f46e23bb48e
Revises: 4761f7065f42
Create Date: 2026-05-11 16:56:20.088254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f46e23bb48e'
down_revision: Union[str, Sequence[str], None] = '4761f7065f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlcs',
    sa.Column('ohlc_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ohlc_id')
    )
    op.create_index('idx_ohlc_source_symbol', 'ohlcs', ['source', 'symbol'], unique=False)
    op.drop_index(op.f('idx_ohlc_levels_source_symbol'), table_name='ohlc_levels')
    op.drop_table('ohlc_levels')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlc_levels',
    sa.Column('ohlc_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ohlc_id', name=op.f('ohlc_levels_pkey'))
    )
    op.create_index(op.f('idx_ohlc_levels_source_symbol'), 'ohlc_levels', ['source', 'symbol'], unique=False)
    op.drop_index('idx_ohlc_levels_source_symbol', table_name='ohlcs')
    op.drop_table('ohlcs')
    # ### end Alembic commands ###
