"""Changed strategy_deployment_orders.broker_order_id to null

Revision ID: 116e8e60741d
Revises: 25ef00d4b495
Create Date: 2026-05-19 11:09:44.617890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116e8e60741d'
down_revision: Union[str, Sequence[str], None] = '25ef00d4b495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strategy_deployment_orders', 'broker_order_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strategy_deployment_orders', 'broker_order_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
