"""renamed ticker to symbol in strategy_deployments

Revision ID: 134856aac368
Revises: 999917f03966
Create Date: 2025-12-10 12:36:38.086583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134856aac368'
down_revision: Union[str, Sequence[str], None] = '999917f03966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("alter table strategy_deployments rename column ticker to symbol")
    # op.add_column('strategy_deployments', sa.Column('symbol', sa.String(), nullable=False))
    # op.drop_column('strategy_deployments', 'ticker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('strategy_deployments', sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.drop_column('strategy_deployments', 'symbol')
    op.execute("alter table strategy_deployments rename column symbol to ticker")
    # ### end Alembic commands ###
