"""Added market field to market_data

Revision ID: 13d44438f93b
Revises: 5104d0bec4d9
Create Date: 2025-12-06 21:06:10.039912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d44438f93b'
down_revision: Union[str, Sequence[str], None] = '5104d0bec4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # try:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data', sa.Column('market_type', sa.String(), nullable=False))
    # except:
    #     pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data', 'market_type')
    # ### end Alembic commands ###
