"""Added market_type field to strategy_deployments

Revision ID: 1e1162ffa897
Revises: 4afb743dc94e
Create Date: 2026-05-14 15:19:15.442381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e1162ffa897'
down_revision: Union[str, Sequence[str], None] = '4afb743dc94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_deployments', sa.Column('market_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_deployments', 'market_type')
    # ### end Alembic commands ###
