"""Added equity_curve and balance_curve fields to bakctest metrics

Revision ID: 253863c98893
Revises: 82a2604a9b52
Create Date: 2026-05-18 12:52:53.990964

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "253863c98893"
down_revision: Union[str, Sequence[str], None] = "82a2604a9b52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "backtest_metrics",
        sa.Column(
            "equity_curve",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.add_column(
        "backtest_metrics",
        sa.Column(
            "balance_curve",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("backtest_metrics", "balance_curve")
    op.drop_column("backtest_metrics", "equity_curve")
    # ### end Alembic commands ###
