"""Changed strategy_deployment_orders.notional to nulable

Revision ID: 25ef00d4b495
Revises: 8f9bcf2598e0
Create Date: 2026-05-19 11:02:40.873743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ef00d4b495'
down_revision: Union[str, Sequence[str], None] = '8f9bcf2598e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strategy_deployment_orders', 'notional',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strategy_deployment_orders', 'notional',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
