"""Added strategy_deployment_orders table

Revision ID: 280feffe2f44
Revises: 6a6328e91c45
Create Date: 2026-05-14 10:39:56.258947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280feffe2f44'
down_revision: Union[str, Sequence[str], None] = '6a6328e91c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_deployment_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('notional', sa.Float(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('candle_ts', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('broker_order_id', sa.String(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['strategy_deployments.deployment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_deployment_orders_broker_order_id'), 'strategy_deployment_orders', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_strategy_deployment_orders_deployment_id'), 'strategy_deployment_orders', ['deployment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_deployment_orders_deployment_id'), table_name='strategy_deployment_orders')
    op.drop_index(op.f('ix_strategy_deployment_orders_broker_order_id'), table_name='strategy_deployment_orders')
    op.drop_table('strategy_deployment_orders')
    # ### end Alembic commands ###
