"""Added market_type field to ohlcs, created backtest equity curve table

Revision ID: 2a4c2bdc023e
Revises: 0f46e23bb48e
Create Date: 2026-05-13 19:45:19.750956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a4c2bdc023e'
down_revision: Union[str, Sequence[str], None] = '0f46e23bb48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_equity_curve',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backtest_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('equity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_equity_curve_timestamp'), 'backtest_equity_curve', ['timestamp'], unique=False)
    op.add_column('backtest_metrics', sa.Column('profit_factor', sa.Float(), nullable=False))
    op.drop_constraint(op.f('backtest_metrics_backtest_id_fkey'), 'backtest_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'backtest_metrics', 'backtests', ['backtest_id'], ['id'], ondelete='CASCADE')
    op.drop_column('backtest_metrics', 'sharpe_ratio')
    op.drop_column('backtest_orders', 'broker')
    op.add_column('ohlcs', sa.Column('market_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ohlcs', 'market_type')
    op.add_column('backtest_orders', sa.Column('broker', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('backtest_metrics', sa.Column('sharpe_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'backtest_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('backtest_metrics_backtest_id_fkey'), 'backtest_metrics', 'backtests', ['backtest_id'], ['id'])
    op.drop_column('backtest_metrics', 'profit_factor')
    op.drop_index(op.f('ix_backtest_equity_curve_timestamp'), table_name='backtest_equity_curve')
    op.drop_table('backtest_equity_curve')
    # ### end Alembic commands ###
