"""Added market_type field to backtests

Revision ID: 2a7cabc0a7d2
Revises: c2cb1304719d
Create Date: 2026-05-14 19:38:11.515801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7cabc0a7d2'
down_revision: Union[str, Sequence[str], None] = 'c2cb1304719d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtests', sa.Column('market_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtests', 'market_type')
    # ### end Alembic commands ###
