"""Added updated_at field to backtests

Revision ID: 3a48f4277e3d
Revises: 59e7096da7f1
Create Date: 2026-05-24 11:01:21.450299

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3a48f4277e3d"
down_revision: Union[str, Sequence[str], None] = "59e7096da7f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "backtests", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )

    op.execute("""
        UPDATE backtests
        SET updated_at = NOW()
        WHERE updated_at IS NULL
        """)

    op.alter_column("backtests", "updated_at", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("backtests", "updated_at")
    # ### end Alembic commands ###
