"""Added updated_at field to event_outbox

Revision ID: 3c5015517ba9
Revises: eaaf23075b19
Create Date: 2026-05-22 08:24:02.687757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5015517ba9'
down_revision: Union[str, Sequence[str], None] = 'eaaf23075b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_outbox', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('event_outbox', 'topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_outbox', sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('event_outbox', 'updated_at')
    # ### end Alembic commands ###
