"""Added market_type field to ohlcs

Revision ID: 471d78ca5e15
Revises: 2a4c2bdc023e
Create Date: 2026-05-13 19:47:15.730313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '471d78ca5e15'
down_revision: Union[str, Sequence[str], None] = '2a4c2bdc023e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
