"""Removed response payload field from strategy_deployment_orders

Revision ID: 4afb743dc94e
Revises: 280feffe2f44
Create Date: 2026-05-14 12:51:41.895394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4afb743dc94e'
down_revision: Union[str, Sequence[str], None] = '280feffe2f44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('strategy_deployment_orders', 'response_payload')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('strategy_deployment_orders', sa.Column('response_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
