"""Added notifications table adn removed key from strategy deployment orders

Revision ID: 50d056dfc07b
Revises: 0cb2104874ae
Create Date: 2026-06-07 11:41:14.405911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50d056dfc07b'
down_revision: Union[str, Sequence[str], None] = '0cb2104874ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channel_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('strategy_deployment_orders', 'key')
    op.drop_column('strategy_deployment_orders', 'candle_ts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_deployment_orders', sa.Column('candle_ts', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('strategy_deployment_orders', sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('notifications')
    # ### end Alembic commands ###
