"""Added uniqeue constraint on (source, key) in markt data

Revision ID: 5104d0bec4d9
Revises: 8071e8765225
Create Date: 2025-12-06 18:57:46.886885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5104d0bec4d9'
down_revision: Union[str, Sequence[str], None] = '8071e8765225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('market_data_source_timestamp_key'), 'market_data', type_='unique')
    op.create_unique_constraint(None, 'market_data', ['source', 'key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'market_data', type_='unique')
    op.create_unique_constraint(op.f('market_data_source_timestamp_key'), 'market_data', ['source', 'timestamp'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
