"""Removed symbol, broker, timeframe columns from strategy_deployments

Revision ID: 5391f1ccb15a
Revises: 3a48f4277e3d
Create Date: 2026-05-24 12:12:59.292547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5391f1ccb15a'
down_revision: Union[str, Sequence[str], None] = '3a48f4277e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('strategy_deployments_instrument_id_fkey'), 'strategy_deployments', type_='foreignkey')
    op.drop_column('strategy_deployments', 'instrument_id')
    op.drop_column('strategy_deployments', 'timeframe')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_deployments', sa.Column('timeframe', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('strategy_deployments', sa.Column('instrument_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('strategy_deployments_instrument_id_fkey'), 'strategy_deployments', 'instruments', ['instrument_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
