"""Removed ohlc_loader_checkpoints table

Revision ID: 54bdba8b5128
Revises: d01dcaad35f0
Create Date: 2026-05-14 10:02:04.837223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54bdba8b5128'
down_revision: Union[str, Sequence[str], None] = 'd01dcaad35f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ohlc_loader_checkpoint_lookup'), table_name='ohlc_loader_checkpoints')
    op.drop_table('ohlc_loader_checkpoints')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlc_loader_checkpoints',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('broker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('market_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ohlc_loader_checkpoints_pkey'))
    )
    op.create_index(op.f('idx_ohlc_loader_checkpoint_lookup'), 'ohlc_loader_checkpoints', ['broker', 'symbol', 'market_type', 'timeframe'], unique=False)
    # ### end Alembic commands ###
