"""Dropped non null constraint on strategy code

Revision ID: 59e7096da7f1
Revises: 9c442ad13abb
Create Date: 2026-05-23 21:15:04.343212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e7096da7f1'
down_revision: Union[str, Sequence[str], None] = '9c442ad13abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strategy', 'code',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strategy', 'code',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
