"""added prompt field to strategies

Revision ID: 63095b25b7ab
Revises: cb75de1fb94f
Create Date: 2025-12-11 16:40:45.595952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63095b25b7ab'
down_revision: Union[str, Sequence[str], None] = 'cb75de1fb94f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('prompt', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'prompt')
    # ### end Alembic commands ###
