"""added server_data field to backtests and strategy_deployments

Revision ID: 637030fea793
Revises: a1b2c3d4e5f6
Create Date: 2025-12-08 15:06:53.080035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '637030fea793'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # op.add_column('backtests', sa.Column('server_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.execute("alter table backtests add column server_data jsonb")
    op.execute("update backtests set server_data = '{}' where server_data is null")
    op.execute("alter table backtests alter column server_data set not null")
    
    op.add_column('broker_connections', sa.Column('broker_account_id', sa.String(), nullable=False))
    
    # op.add_column('strategy_deployments', sa.Column('server_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.execute("alter table strategy_deployments add column server_data jsonb")
    op.execute("update strategy_deployments set server_data = '{}' where server_data is null")
    op.execute("alter table strategy_deployments alter column server_data set not null")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_deployments', 'server_data')
    op.drop_column('broker_connections', 'broker_account_id')
    op.drop_column('backtests', 'server_data')
    # ### end Alembic commands ###
