"""starting_balance nullable in strategy_deployments

Revision ID: 73d3b37bdf64
Revises: 134856aac368
Create Date: 2025-12-10 16:16:39.383267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73d3b37bdf64'
down_revision: Union[str, Sequence[str], None] = '134856aac368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strategy_deployments', 'starting_balance',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_column('strategy_deployments', 'config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_deployments', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('strategy_deployments', 'starting_balance',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
