"""created tables

Revision ID: 7588e14328cd
Revises: 
Create Date: 2025-12-07 19:11:08.732164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7588e14328cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticks',
    sa.Column('tick_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('market_type', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('tick_id'),
    sa.UniqueConstraint('source', 'key')
    )
    op.create_index('idx_ticks_source_timestamp', 'ticks', ['source', 'timestamp'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('jwt', sa.String(), nullable=True),
    sa.Column('pricing_tier', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('authenticated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('broker_connections',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('broker', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('oauth_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('connection_id')
    )
    op.create_table('strategies',
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('strategy_id'),
    sa.UniqueConstraint('user_id', 'name')
    )
    op.create_table('backtests',
    sa.Column('backtest_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.strategy_id'], ),
    sa.PrimaryKeyConstraint('backtest_id')
    )
    op.create_table('strategy_deployments',
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('broker_connection_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['broker_connection_id'], ['broker_connections.connection_id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.strategy_id'], ),
    sa.PrimaryKeyConstraint('deployment_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=8), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=15, scale=8), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('average_fill_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('time_in_force', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_order_id', sa.String(), nullable=True),
    sa.Column('broker_order_id', sa.String(), nullable=True),
    sa.Column('backtest_id', sa.UUID(), nullable=True),
    sa.Column('deployment_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.backtest_id'], ),
    sa.ForeignKeyConstraint(['deployment_id'], ['strategy_deployments.deployment_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('strategy_deployments')
    op.drop_table('backtests')
    op.drop_table('strategies')
    op.drop_table('broker_connections')
    op.drop_table('users')
    op.drop_index('idx_ticks_source_timestamp', table_name='ticks')
    op.drop_table('ticks')
    # ### end Alembic commands ###
