"""
Added user_id and metrics column to strategies

Revision ID: 7c680a512404
Revises: 0019a7043609
Create Date: 2025-12-07 18:59:39.590860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c680a512404'
down_revision: Union[str, Sequence[str], None] = '0019a7043609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('strategies', sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint(None, 'strategies', ['user_id', 'name'])
    op.create_foreign_key(None, 'strategies', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strategies', type_='foreignkey')
    op.drop_constraint(None, 'strategies', type_='unique')
    op.drop_column('strategies', 'metrics')
    op.drop_column('strategies', 'user_id')
    # ### end Alembic commands ###
