"""Created foreign keys and cascading

Revision ID: 7fa5faeed9e0
Revises: cb02fd3a581e
Create Date: 2026-01-24 11:38:43.100312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa5faeed9e0'
down_revision: Union[str, Sequence[str], None] = 'cb02fd3a581e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('backtests_strategy_id_fkey'), 'backtests', type_='foreignkey')
    op.create_foreign_key(None, 'backtests', 'strategies', ['strategy_id'], ['strategy_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('orders_deployment_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_backtest_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'backtests', ['backtest_id'], ['backtest_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'strategy_deployments', ['deployment_id'], ['deployment_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('strategies_user_id_fkey'), 'strategies', type_='foreignkey')
    op.create_foreign_key(None, 'strategies', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('strategy_deployments_strategy_id_fkey'), 'strategy_deployments', type_='foreignkey')
    op.drop_constraint(op.f('strategy_deployments_broker_connection_id_fkey'), 'strategy_deployments', type_='foreignkey')
    op.create_foreign_key(None, 'strategy_deployments', 'strategies', ['strategy_id'], ['strategy_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'strategy_deployments', 'broker_connections', ['broker_connection_id'], ['connection_id'], ondelete='CASCADE')
    op.drop_column('strategy_deployments', 'market_type')
    op.drop_column('ticks', 'market_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticks', sa.Column('market_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('strategy_deployments', sa.Column('market_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'strategy_deployments', type_='foreignkey')
    op.drop_constraint(None, 'strategy_deployments', type_='foreignkey')
    op.create_foreign_key(op.f('strategy_deployments_broker_connection_id_fkey'), 'strategy_deployments', 'broker_connections', ['broker_connection_id'], ['connection_id'])
    op.create_foreign_key(op.f('strategy_deployments_strategy_id_fkey'), 'strategy_deployments', 'strategies', ['strategy_id'], ['strategy_id'])
    op.drop_constraint(None, 'strategies', type_='foreignkey')
    op.create_foreign_key(op.f('strategies_user_id_fkey'), 'strategies', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_backtest_id_fkey'), 'orders', 'backtests', ['backtest_id'], ['backtest_id'])
    op.create_foreign_key(op.f('orders_deployment_id_fkey'), 'orders', 'strategy_deployments', ['deployment_id'], ['deployment_id'])
    op.drop_constraint(None, 'backtests', type_='foreignkey')
    op.create_foreign_key(op.f('backtests_strategy_id_fkey'), 'backtests', 'strategies', ['strategy_id'], ['strategy_id'])
    # ### end Alembic commands ###
