"""Added uniqeue constraint on (source, timestamp) in markt data

Revision ID: 8071e8765225
Revises: bcb7ac93df38
Create Date: 2025-12-06 18:56:27.241350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8071e8765225'
down_revision: Union[str, Sequence[str], None] = 'bcb7ac93df38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'market_data', ['source', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'market_data', type_='unique')
    # ### end Alembic commands ###
