"""Removed user_id and name unique constraint in strategy table

Revision ID: 82a2604a9b52
Revises: f730e4831bba
Create Date: 2026-05-17 19:09:08.059984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a2604a9b52'
down_revision: Union[str, Sequence[str], None] = 'f730e4831bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('strategy_user_id_name_key'), 'strategy', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('strategy_user_id_name_key'), 'strategy', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
