"""Added timestamp field to updated_at

Revision ID: 83ec7445d5f1
Revises: 3c5015517ba9
Create Date: 2026-05-22 08:27:58.924709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83ec7445d5f1'
down_revision: Union[str, Sequence[str], None] = '3c5015517ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_outbox', sa.Column('timestamp', sa.Integer(), nullable=False))
    op.drop_column('event_outbox', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_outbox', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('event_outbox', 'timestamp')
    # ### end Alembic commands ###
