"""Added instrument_id column to strategy_deployments

Revision ID: 8f9bcf2598e0
Revises: af967ba36c2a
Create Date: 2026-05-19 09:22:55.734787

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8f9bcf2598e0"
down_revision: Union[str, Sequence[str], None] = "af967ba36c2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "strategy_deployments", sa.Column("instrument_id", sa.UUID(), nullable=True)
    )

    op.execute("""
        UPDATE strategy_deployments d
        SET instrument_id = i.id
        FROM instruments i
        WHERE
            i.symbol = d.symbol AND
            i.market_type = d.market_type AND
            i.broker_type = d.broker
    """)

    op.alter_column("strategy_deployments", "instrument_id", nullable=False)

    op.create_foreign_key(
        None,
        "strategy_deployments",
        "instruments",
        ["instrument_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("strategy_deployments", "market_type")
    op.drop_column("strategy_deployments", "symbol")
    op.drop_column("strategy_deployments", "broker")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.add_column(
        "strategy_deployments",
        sa.Column("symbol", sa.String(), nullable=True),
    )

    op.add_column(
        "strategy_deployments",
        sa.Column("market_type", sa.String(), nullable=True),
    )

    op.add_column(
        "strategy_deployments",
        sa.Column("broker", sa.String(), nullable=True),
    )

    op.execute("""
        UPDATE strategy_deployments d
        SET
            symbol = i.symbol,
            market_type = i.market_type,
            broker = i.broker_type
        FROM instruments i
        WHERE d.instrument_id = i.id
    """)

    op.alter_column("strategy_deployments", "symbol", nullable=False)
    op.alter_column("strategy_deployments", "market_type", nullable=False)
    op.alter_column("strategy_deployments", "broker", nullable=False)

    op.drop_constraint(
        "fk_strategy_deployments_instrument_id",
        "strategy_deployments",
        type_="foreignkey",
    )

    op.drop_column("strategy_deployments", "instrument_id")