"""Removed

Revision ID: 990a2cc3d568
Revises: 6c6003ecc6e1
Create Date: 2026-05-23 19:46:30.032382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "990a2cc3d568"
down_revision: Union[str, Sequence[str], None] = "6c6003ecc6e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_ticks_source_timestamp"), table_name="ticks")
    op.drop_table("ticks")
    op.drop_table("orders")
    op.drop_table("account_snapshots")
    op.drop_index(
        op.f("ix_backtest_equity_curve_timestamp"), table_name="backtest_equity_curve"
    )
    op.drop_table("backtest_equity_curve")
    op.drop_constraint(
        op.f("backtests_instrument_id_fkey"), "backtests", type_="foreignkey"
    )
    op.drop_constraint(op.f("users_stripe_customer_id_key"), "users", type_="unique")
    op.drop_column("users", "stripe_customer_id")
    op.drop_column("users", "pricing_tier")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("pricing_tier", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column(
            "stripe_customer_id", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.create_unique_constraint(
        op.f("users_stripe_customer_id_key"),
        "users",
        ["stripe_customer_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_foreign_key(
        op.f("backtests_instrument_id_fkey"),
        "backtests",
        "instruments",
        ["instrument_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_table(
        "backtest_equity_curve",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("backtest_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("timestamp", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "balance",
            sa.NUMERIC(precision=20, scale=8),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "equity",
            sa.NUMERIC(precision=20, scale=8),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["backtest_id"],
            ["backtests.id"],
            name=op.f("backtest_equity_curve_backtest_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("backtest_equity_curve_pkey")),
    )
    op.create_index(
        op.f("ix_backtest_equity_curve_timestamp"),
        "backtest_equity_curve",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "account_snapshots",
        sa.Column("snapshot_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("deployment_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("snapshot_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["strategy_deployments.deployment_id"],
            name=op.f("account_snapshots_deployment_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("account_snapshots_pkey")),
    )
    op.create_table(
        "orders",
        sa.Column("order_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("symbol", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("side", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("order_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "quantity",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "notional",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "filled_quantity",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "limit_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "stop_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "avg_fill_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "submitted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "filled_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("broker_order_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("backtest_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("deployment_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["backtest_id"],
            ["backtests.id"],
            name=op.f("orders_backtest_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["strategy_deployments.deployment_id"],
            name=op.f("orders_deployment_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("order_id", name=op.f("orders_pkey")),
    )
    op.create_table(
        "ticks",
        sa.Column("tick_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("symbol", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "size",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("timestamp", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("tick_id", name=op.f("ticks_pkey")),
        sa.UniqueConstraint(
            "source",
            "key",
            name=op.f("ticks_source_key_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_ticks_source_timestamp"),
        "ticks",
        ["source", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###
