"""renamed average fil price column to avg_fill_price

Revision ID: 999917f03966
Revises: fb9abcc3c4a7
Create Date: 2025-12-10 09:38:46.993740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999917f03966'
down_revision: Union[str, Sequence[str], None] = 'fb9abcc3c4a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('orders', sa.Column('avg_fill_price', sa.Numeric(precision=15, scale=2), nullable=True))
    # op.drop_column('orders', 'average_fill_price')
    op.execute("alter table orders rename column average_fill_price to avg_fill_price")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('orders', sa.Column('average_fill_price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    # op.drop_column('orders', 'avg_fill_price')
    op.execute("alter table orders rename column avg_fill_price to average_fill_price")
    # ### end Alembic commands ###
