"""Added email_verification_code

Revision ID: 9b191341ff7b
Revises: 50d056dfc07b
Create Date: 2026-06-10 10:34:06.322107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b191341ff7b'
down_revision: Union[str, Sequence[str], None] = '50d056dfc07b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verification_token', sa.String(), nullable=True))
    op.execute("ALTER TABLE users RENAME COLUMN authenticated_at TO email_verified_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_token')
    op.execute("ALTER TABLE users RENAME COLUMN email_verified_at TO authenticated_at")
    # ### end Alembic commands ###
