"""Removed timeframe column from backtests

Revision ID: 9c442ad13abb
Revises: 990a2cc3d568
Create Date: 2026-05-23 21:09:54.173072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c442ad13abb'
down_revision: Union[str, Sequence[str], None] = '990a2cc3d568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtests', 'timeframe')
    op.drop_column('backtests', 'instrument_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtests', sa.Column('instrument_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('backtests', sa.Column('timeframe', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
