"""Removed broker metadata field from orders and add details field to orders

Revision ID: a277b12f5c5b
Revises: ba61b62da554
Create Date: 2026-01-25 15:18:41.843240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a277b12f5c5b'
down_revision: Union[str, Sequence[str], None] = 'ba61b62da554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snapshots',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['strategy_deployments.deployment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.add_column('orders', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('orders', 'broker_metadata')
    op.drop_column('orders', 'client_order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('client_order_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('broker_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('orders', 'details')
    op.drop_table('account_snapshots')
    # ### end Alembic commands ###
