"""Removed non nul constraint on prompt

Revision ID: a491cc26c1e0
Revises: 5391f1ccb15a
Create Date: 2026-05-24 15:31:19.733622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a491cc26c1e0'
down_revision: Union[str, Sequence[str], None] = '5391f1ccb15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strategy', 'prompt',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strategy', 'prompt',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
