"""Added instrument_id column to backtests

Revision ID: af967ba36c2a
Revises: 34a55dd3549e
Create Date: 2026-05-19 09:02:23.199116

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "af967ba36c2a"
down_revision: Union[str, Sequence[str], None] = "34a55dd3549e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("backtests", sa.Column("instrument_id", sa.UUID(), nullable=True))

    op.execute("""
        UPDATE backtests b
        SET instrument_id = i.id
        FROM instruments i
        WHERE
            i.symbol = b.symbol
            AND i.market_type = b.market_type
            AND i.broker_type = b.broker
    """)

    op.alter_column("backtests", "instrument_id", nullable=False)
    op.create_foreign_key(
        None, "backtests", "instruments", ["instrument_id"], ["id"], ondelete="CASCADE"
    )

    op.drop_column("backtests", "market_type")
    op.drop_column("backtests", "broker")
    op.drop_column("backtests", "symbol")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "backtests",
        sa.Column("symbol", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "backtests",
        sa.Column("broker", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "backtests",
        sa.Column("market_type", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "backtests", type_="foreignkey")
    op.drop_column("backtests", "instrument_id")
    # ### end Alembic commands ###
