"""Removed time_in_force field from orders

Revision ID: ba61b62da554
Revises: d2a3d6f243ba
Create Date: 2026-01-24 20:59:04.711708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba61b62da554'
down_revision: Union[str, Sequence[str], None] = 'd2a3d6f243ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'time_in_force')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('time_in_force', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
