"""Created market data table

Revision ID: bcb7ac93df38
Revises: 25a29b22f18e
Create Date: 2025-12-06 18:44:50.851313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcb7ac93df38'
down_revision: Union[str, Sequence[str], None] = '25a29b22f18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data',
    sa.Column('market_data_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('market_data_id')
    )
    op.create_table('strategies',
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('strategy_id')
    )
    op.create_table('backtests',
    sa.Column('backtest_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.strategy_id'], ),
    sa.PrimaryKeyConstraint('backtest_id')
    )
    op.create_table('broker_connections',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('broker', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('oauth_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('connection_id')
    )
    op.create_table('live_deployments',
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('broker_connection_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['broker_connection_id'], ['broker_connections.connection_id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.strategy_id'], ),
    sa.PrimaryKeyConstraint('deployment_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=8), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=15, scale=8), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('average_fill_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('time_in_force', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_order_id', sa.String(), nullable=True),
    sa.Column('broker_order_id', sa.String(), nullable=True),
    sa.Column('backtest_id', sa.UUID(), nullable=True),
    sa.Column('deployment_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.backtest_id'], ),
    sa.ForeignKeyConstraint(['deployment_id'], ['live_deployments.deployment_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('live_deployments')
    op.drop_table('broker_connections')
    op.drop_table('backtests')
    op.drop_table('strategies')
    op.drop_table('market_data')
    # ### end Alembic commands ###
