"""Added ohlc_loader_checkpoints table

Revision ID: c1b32324e5ec
Revises: f21265f5bd3f
Create Date: 2026-05-13 22:44:44.598520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b32324e5ec'
down_revision: Union[str, Sequence[str], None] = 'f21265f5bd3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlc_loader_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('broker', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('market_type', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('start_timestamp', sa.Integer(), nullable=False),
    sa.Column('end_timestamp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ohlc_loader_checkpoint_lookup', 'ohlc_loader_checkpoints', ['broker', 'symbol', 'market_type', 'timeframe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ohlc_loader_checkpoint_lookup', table_name='ohlc_loader_checkpoints')
    op.drop_table('ohlc_loader_checkpoints')
    # ### end Alembic commands ###
