"""Added created_at and updated_at field to broker_connections

Revision ID: c2cb1304719d
Revises: 1e1162ffa897
Create Date: 2026-05-14 17:22:25.824212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2cb1304719d'
down_revision: Union[str, Sequence[str], None] = '1e1162ffa897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_connections', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('broker_connections', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('strategy_deployments', 'starting_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_deployments', sa.Column('starting_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('broker_connections', 'updated_at')
    op.drop_column('broker_connections', 'created_at')
    # ### end Alembic commands ###
