"""x

Revision ID: cb02fd3a581e
Revises: bbd2c5100092
Create Date: 2025-12-12 21:04:37.177735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb02fd3a581e'
down_revision: Union[str, Sequence[str], None] = 'bbd2c5100092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlc_levels',
    sa.Column('ohlc_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ohlc_id')
    )
    op.create_index('idx_ohlc_levels_source_symbol', 'ohlc_levels', ['source', 'symbol'], unique=False)
    op.alter_column('backtests', 'starting_balance',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('orders', 'quantity',
               existing_type=sa.NUMERIC(precision=15, scale=8),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('orders', 'filled_quantity',
               existing_type=sa.NUMERIC(precision=15, scale=8),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('orders', 'limit_price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('orders', 'stop_price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('orders', 'avg_fill_price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('strategy_deployments', 'starting_balance',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('ticks', 'price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ticks', 'size',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticks', 'size',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('ticks', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('strategy_deployments', 'starting_balance',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('orders', 'avg_fill_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('orders', 'stop_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('orders', 'limit_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('orders', 'filled_quantity',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=8),
               existing_nullable=False)
    op.alter_column('orders', 'quantity',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=8),
               existing_nullable=False)
    op.alter_column('backtests', 'starting_balance',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.drop_index('idx_ohlc_levels_source_symbol', table_name='ohlc_levels')
    op.drop_table('ohlc_levels')
    # ### end Alembic commands ###
