"""added market type to strategy deployments

Revision ID: cb75de1fb94f
Revises: 73d3b37bdf64
Create Date: 2025-12-10 16:41:20.447733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb75de1fb94f'
down_revision: Union[str, Sequence[str], None] = '73d3b37bdf64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_deployments', sa.Column('market_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_deployments', 'market_type')
    # ### end Alembic commands ###
