"""Added notional field to orders

Revision ID: cdc2724b41a6
Revises: 7185ee7e07a5
Create Date: 2026-01-25 15:53:24.655518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc2724b41a6'
down_revision: Union[str, Sequence[str], None] = '7185ee7e07a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('notional', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'notional')
    # ### end Alembic commands ###
