"""Added start_date and end_date columns to ohlc_loader_checkpoints. Removed start_timestamp and end_timestamp

Revision ID: d01dcaad35f0
Revises: c1b32324e5ec
Create Date: 2026-05-13 22:55:17.341987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01dcaad35f0'
down_revision: Union[str, Sequence[str], None] = 'c1b32324e5ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohlc_loader_checkpoints', sa.Column('start_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('ohlc_loader_checkpoints', sa.Column('end_date', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('ohlc_loader_checkpoints', 'start_timestamp')
    op.drop_column('ohlc_loader_checkpoints', 'end_timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohlc_loader_checkpoints', sa.Column('end_timestamp', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('ohlc_loader_checkpoints', sa.Column('start_timestamp', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('ohlc_loader_checkpoints', 'end_date')
    op.drop_column('ohlc_loader_checkpoints', 'start_date')
    # ### end Alembic commands ###
