"""Added api_key and secret_key fields to broker_connections

Revision ID: d2a3d6f243ba
Revises: 7fa5faeed9e0
Create Date: 2026-01-24 20:28:46.964417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a3d6f243ba'
down_revision: Union[str, Sequence[str], None] = '7fa5faeed9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_connections', sa.Column('secret_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broker_connections', 'secret_key')
    # ### end Alembic commands ###
