"""add_user_id_to_strategy_versions_deployments_backtests

Revision ID: e1ac930934f7
Revises: 9b191341ff7b
Create Date: 2026-06-10 13:34:48.336072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ac930934f7'
down_revision: Union[str, Sequence[str], None] = '9b191341ff7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtests', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key('backtests_user_id_fkey', 'backtests', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.add_column('backtests', sa.Column('strategy_id', sa.UUID(), nullable=False))
    op.create_foreign_key('backtests_strategy_id_fkey', 'backtests', 'strategy', ['strategy_id'], ['strategy_id'], ondelete='CASCADE')
    op.add_column('strategy_deployments', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key('strategy_deployments_user_id_fkey', 'strategy_deployments', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.add_column('strategy_deployments', sa.Column('strategy_id', sa.UUID(), nullable=False))
    op.create_foreign_key('strategy_deployments_strategy_id_fkey', 'strategy_deployments', 'strategy', ['strategy_id'], ['strategy_id'], ondelete='CASCADE')
    op.add_column('strategy_versions', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key('strategy_versions_user_id_fkey', 'strategy_versions', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('strategy_versions_user_id_fkey', 'strategy_versions', type_='foreignkey')
    op.drop_column('strategy_versions', 'user_id')
    op.drop_constraint('strategy_deployments_strategy_id_fkey', 'strategy_deployments', type_='foreignkey')
    op.drop_column('strategy_deployments', 'strategy_id')
    op.drop_constraint('strategy_deployments_user_id_fkey', 'strategy_deployments', type_='foreignkey')
    op.drop_column('strategy_deployments', 'user_id')
    op.drop_constraint('backtests_strategy_id_fkey', 'backtests', type_='foreignkey')
    op.drop_column('backtests', 'strategy_id')
    op.drop_constraint('backtests_user_id_fkey', 'backtests', type_='foreignkey')
    op.drop_column('backtests', 'user_id')
    # ### end Alembic commands ###
