"""Added strategy version table

Revision ID: e73d01721878
Revises: a491cc26c1e0
Create Date: 2026-05-27 13:58:11.070612

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e73d01721878"
down_revision: Union[str, Sequence[str], None] = "a491cc26c1e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "strategy_version",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("strategy_id", sa.UUID(), nullable=False),
        sa.Column("prev_version", sa.UUID(), nullable=True),
        sa.Column("code", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["prev_version"], ["strategy_version.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"], ["strategy.strategy_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.execute("""
    INSERT INTO strategy_version (id, strategy_id, prev_version, code, created_at, updated_at)
    SELECT gen_random_uuid(), strategy_id, NULL, code, created_at, updated_at
    FROM strategy;
    """)

    op.create_table(
        "backtest_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("backtest_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["backtest_id"], ["backtests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.add_column("strategy", sa.Column("cur_version_id", sa.UUID(), nullable=True))
    op.drop_column("strategy", "prompt")
    op.drop_column("strategy", "code")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "strategy", sa.Column("code", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.execute("""
    UPDATE strategy s
    SET code = sv.code
    FROM strategy_version sv
    WHERE s.cur_version_id = sv.id;
    """)

    op.add_column(
        "strategy", sa.Column("prompt", sa.TEXT(), autoincrement=False, nullable=True)
    )
    
    op.drop_column("strategy", "cur_version_id")

    op.drop_table("backtest_events")
    op.drop_table("strategy_version")
    # ### end Alembic commands ###
