"""Added volume field to ohlcs

Revision ID: f21265f5bd3f
Revises: 471d78ca5e15
Create Date: 2026-05-13 20:15:41.957721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f21265f5bd3f'
down_revision: Union[str, Sequence[str], None] = '471d78ca5e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohlcs', sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ohlcs', 'volume')
    # ### end Alembic commands ###
