"""Removed balance_curve field from backtest_metrics

Revision ID: f4557e0dbe9b
Revises: 253863c98893
Create Date: 2026-05-18 13:01:01.917142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4557e0dbe9b'
down_revision: Union[str, Sequence[str], None] = '253863c98893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
