"""_

Revision ID: f730e4831bba
Revises: b709ebcf7be5
Create Date: 2026-05-17 17:53:27.629812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f730e4831bba'
down_revision: Union[str, Sequence[str], None] = 'b709ebcf7be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column("strategy", "metrics")
    op.create_table('strategy_deployment_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('realised_pnl', sa.Float(), nullable=False),
    sa.Column('unrealised_pnl', sa.Float(), nullable=False),
    sa.Column('total_return_pct', sa.Float(), nullable=False),
    sa.Column('profit_factor', sa.Float(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['strategy_deployments.deployment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deployment_id')
    )
    op.alter_column('backtests', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('backtests', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('backtests_strategy_id_fkey'), 'backtests', type_='foreignkey')
    op.create_foreign_key(None, 'backtests', 'strategy', ['strategy_id'], ['strategy_id'], ondelete='CASCADE')
    op.add_column('broker_connections', sa.Column('broker_account_number', sa.String(), nullable=False))
    op.add_column('strategy_deployment_orders', sa.Column('filled_quantity', sa.Float(), nullable=False))
    op.add_column('strategy_deployment_orders', sa.Column('avg_fill_price', sa.Float(), nullable=True))
    op.alter_column('strategy_deployment_orders', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('strategy_deployment_orders', 'notional',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('strategy_deployment_orders', 'limit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('strategy_deployment_orders', 'stop_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('strategy_deployment_orders', 'broker_order_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('strategy_deployment_orders', 'request_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.add_column('strategy_deployments', sa.Column('broker', sa.String(), nullable=False))
    op.drop_constraint(op.f('strategy_deployments_strategy_id_fkey'), 'strategy_deployments', type_='foreignkey')
    op.create_foreign_key(None, 'strategy_deployments', 'strategy', ['strategy_id'], ['strategy_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strategy_deployments', type_='foreignkey')
    op.create_foreign_key(op.f('strategy_deployments_strategy_id_fkey'), 'strategy_deployments', 'strategies', ['strategy_id'], ['strategy_id'], ondelete='CASCADE')
    op.drop_column('strategy_deployments', 'broker')
    op.alter_column('strategy_deployment_orders', 'request_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('strategy_deployment_orders', 'broker_order_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('strategy_deployment_orders', 'stop_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('strategy_deployment_orders', 'limit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('strategy_deployment_orders', 'notional',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('strategy_deployment_orders', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('strategy_deployment_orders', 'avg_fill_price')
    op.drop_column('strategy_deployment_orders', 'filled_quantity')
    op.drop_column('broker_connections', 'broker_account_number')
    op.drop_constraint(None, 'backtests', type_='foreignkey')
    op.create_foreign_key(op.f('backtests_strategy_id_fkey'), 'backtests', 'strategies', ['strategy_id'], ['strategy_id'], ondelete='CASCADE')
    op.alter_column('backtests', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('backtests', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.create_table('strategies',
    sa.Column('strategy_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('strategies_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('strategy_id', name=op.f('strategies_pkey')),
    sa.UniqueConstraint('user_id', 'name', name=op.f('strategies_user_id_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('strategy_deployment_metrics')
    op.drop_table('strategy')
    # ### end Alembic commands ###
