"""Created ticks table

Revision ID: f7b45f2ec509
Revises: 13d44438f93b
Create Date: 2025-12-06 23:10:40.001357

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f7b45f2ec509"
down_revision: Union[str, Sequence[str], None] = "13d44438f93b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("alter table market_data rename to ticks")
    op.execute("alter table ticks rename column market_data_id to tick_id")
    op.execute("alter table ticks rename constraint market_data_pkey to tick_pkey")
    op.execute(
        "alter table ticks rename constraint market_data_source_key_key to tick_source_key_key"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(
        "alter table ticks rename constraint tick_source_key_key to market_data_source_key_key"
    )
    op.execute("alter table ticks rename constraint tick_pkey to market_data_pkey")
    op.execute("alter table ticks rename column tick_id to market_data_id")
    op.execute("alter table ticks rename to market_data")
