"""Added service_id field to strategy_deployments

Revision ID: feac16857405
Revises: cdc2724b41a6
Create Date: 2026-05-08 17:17:16.529298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feac16857405'
down_revision: Union[str, Sequence[str], None] = 'cdc2724b41a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_deployments', sa.Column('service_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_deployments', 'service_id')
    # ### end Alembic commands ###
