name: Build image
on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Setup
    runs-on: self-hosted

    steps:
      - name: Create .env
        run: |
          set -e

          cat <<'EOF' > .env
          ${{ secrets.ENV_FILE }}
          EOF

          if [ ! -f .env ]; then
            exit 1
          fi

      - name: Initialise swarm manager
        run: sudo docker swarm init || true

      - name: Create network
        run: |
          if ! sudo docker network inspect vegate_network >/dev/null 2>&1; then
            sudo docker network create \
              --driver overlay \
              --attachable vegate_network
          fi

      - name: Docker compose
        run: |
          set -e

          cat <<'EOF' > docker-compose.yaml
          ${{ secrets.INFRA_COMPOSE }}
          EOF

          if [ ! -f docker-compose.yaml ]; then
            exit 1
          fi

          docker compose up -d

  test:
    name: Run Pytest
    runs-on: self-hosted
    needs: setup

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          version: "0.11.16"

      - name: Create .env.test
        run: |
          set -e

          cat <<'EOF' > .env.test
          ${{ secrets.ENV_TEST_FILE }}
          EOF

          if [ ! -f .env.test ]; then
            exit 1
          fi

      - name: Run tests
        run: uv run pytest -s -x

  build:
    name: Build Docker Image
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          set -e

          cat <<'EOF' > .env
          ${{ secrets.ENV_FILE }}
          EOF

          if [ ! -f .env ]; then
            exit 1
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |
          TAG=$(openssl rand -hex 16)

          sudo docker build \
            -f docker/Dockerfile \
            -t wifimemes/vegate-backend:$TAG \
            -t wifimemes/vegate-backend:latest \
            --no-cache \
            .

          sudo docker push wifimemes/vegate-backend:latest
          sudo docker push wifimemes/vegate-backend:$TAG

      - name: Initialise swarm manager
        run: sudo docker swarm init || true

      - name: Create network
        run: |
          if ! sudo docker network inspect vegate_network >/dev/null 2>&1; then
            sudo docker network create \
              --driver overlay \
              --attachable vegate_network
          fi

      - name: Create docker compose
        run: |
          set -e

          cat <<'EOF' > docker/docker-compose.yaml
          ${{ secrets.DOCKER_COMPOSE }}
          EOF

          if [ ! -f docker/docker-compose.yaml ]; then
            exit 1
          fi

      - name: Deploy stack
        run: |
          sudo docker stack deploy \
            -c docker/docker-compose.yaml \
            -d=false \
            vegate_stack

  cleanup:
    name: Cleanup
    runs-on: self-hosted
    if: always()
    needs: [setup, test, build]

    steps:
      - name: Prune images
        run: sudo docker system prune -af
